version: "3.9"

services:
  judger-web:
    build:
      context: ./judger-frontend
      dockerfile: Dockerfile.dev
  
    ports:
      - "8999:4200"
    
    depends_on:
      - judger-api 
    links:
      - judger-api


  judger-api:
    build:
      context: ./judger-backend/judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger-api/.env

    ports:
      - "9001:4003"
    extra_hosts:
      - "host.docker.internal:host-gateway"    

    volumes:
      - /uploads:/usr/src/app/uploads
      - /server-Logs:/usr/src/app/logs
      - ./judger-backend/judger-api:/usr/src/app
      - /usr/src/app/node_modules


  judger:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger/.env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - /uploads:/source
      - /uploads:/io
      - ./judger-backend/judger:/app
      - /app/node_modules


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev

    ports:
     - "9000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    volumes:
     - /server-Logs:/usr/src/app/logs
     - ./auth:/usr/src/app
     - /usr/src/app/node_modules


networks:
  default:
    name: sw-judger_net
    external: true