version: "3.9"

services:
  judger-web:
    build:
      context: ./judger-frontend
      dockerfile: Dockerfile.dev
  
    ports:
      - "8999:4200"

    depends_on:
      - judger-api 


  judger-api:
    build:
      context: ./judger-backend/judger-api
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger-api/.env

    ports:
      - "9001:4003"

    volumes:
      - ./uploads:/uploads
      - ./server-Logs:/usr/src/app/logs
      - ./judger-backend/judger-api:/usr/src/app
      - /usr/src/app/node_modules

    depends_on:
      - mongodb


  judger:
    build:
      context: ./judger-backend/judger
      dockerfile: Dockerfile.dev
    env_file:
      - ./judger-backend/judger/.env

    volumes:
      - ./uploads:/source
      - ./uploads:/io
      - ./judger-backend/judger:/app
      - /app/node_modules
    
    depends_on:
      - mongodb


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev

    ports:
     - "9000:4000"
    
    volumes:
     - ./server-Logs:/usr/src/app/logs
     - ./auth:/usr/src/app
     - /usr/src/app/node_modules

    depends_on:
      - mongodb


  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    
    ports:
      - "27017:27017"

    volumes:
      - ./mongo/mongodb:/data/db


networks:
  default:
    name: sw-judger_net
    external: true