version: '3.9'

services:
  zookeeper:
    image: zookeeper
    
    expose:
      - "2181"
    
    volumes:
      - ./zookeeper/conf:/conf


  kafka:
    image: wurstmeister/kafka
    
    ports:
      - "9999:9092"
    
    networks:
      default:
        aliases:
          - kafka

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 369295700
      KAFKA_BROKER_ID: 1
      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      KAFKA_ADVERTISED_HOST_NAME: kafka

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      
      KAFKA_CREATE_TOPICS: "swjudge-submit:6:1,\
                            swjudge-result:6:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      
      KAFKA_HEAP_OPTS: "-Xms8g -Xmx16g"
    
    depends_on:
      - zookeeper

networks:
  default:
    name: sw-judger_net
    driver: bridge