apiVersion: apps/v1
kind: Deployment
metadata:
  name: judger-auth
  labels:
    app: sw-judger-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-judger-auth
  template:
    metadata:
      labels:
        app: sw-judger-auth
    spec:
      containers:
        - name: sw-judger-auth
          image: sw-judger-auth
          imagePullPolicy: Never #이미지를 도커허브에서 가져올지
          ports:
            - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: judger-auth
spec:
  selector:
    app: sw-judger-auth
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30001
  type: NodePort